# Generated by Django 2.0.8 on 2020-02-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='recipe_des',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='recipe_logo',
            field=models.FileField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
