# Generated by Django 2.0.8 on 2020-02-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200213_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_des', models.CharField(max_length=50)),
                ('recipe_logo', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='recipe_des',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='recipe_logo',
        ),
    ]
