# Generated by Django 2.0.8 on 2020-02-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200213_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.AddField(
            model_name='menu',
            name='des',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
